import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-0 bg-white">
        <div className="flex flex-col h-screen max-h-screen">
          <Header />
          {children}
          <div className="text-center text-sm text-muted-foreground">
            <Separator decorative={true} />
            Powered by{" "}
            <a href="https://markerjs.com/products/diagram" target="blank">
              MJS Diagram
            </a>
          </div>
        </div>
      </body>
    </html>
  );
}
