import Header from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='m-0 bg-white'>
        <div className='flex flex-col h-screen'>
          <Header></Header>
          {children}
        </div>
      </body>
    </html>
  )
}
